name: ecs-ecs-example

services:
  reports:
    build:
      context: .
      target: production
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command:
      - "node"
      - "dist/index.js"